version: "3.4"

services:

  grafana:
    image: grafana/grafana:9.2.4
    container_name: grafana
    volumes:
    - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    ports:
    - "3000:3000"

  loki:
   image: grafana/loki:2.3.0
   container_name: loki
   volumes:
     - ./loki.yml:/etc/config/loki.yaml
   entrypoint:
     - /usr/bin/loki
     - -config.file=/etc/config/loki.yaml
   ports:
     - "3100:3100"

  promtail:
    image: grafana/promtail:2.7.0
    container_name: promtail
    user: root
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./promtail.yml:/etc/config/promtail.yaml
    entrypoint:
      - /usr/bin/promtail
      - -config.file=/etc/config/promtail.yaml
    ports:
      - "9080:9080"

