---
- name: Task 19 docker on servers
  hosts: my_servers
  become: yes

  tasks:
    - name: Ping 
      ping:

    # os type
    - name: check linux os
      debug: var=ansible_os_family

    # install docker
    - name: Install dokcer on amazons linux
      yum: name=docker state=present
      when: ansible_os_family == "RedHat"

    - name: Install docker on ubuntus linux 
      #shell: curl -sSL https://get.docker.com/ | sh # or via get_uri   
      apt: name=docker-ce state=present
      when: ansible_os_family == "Debian"

    # for all 
    - name: Start dokcer
      service: name=docker state=started enabled=yes

   #- name: docker pull image
    #shell: docker pull matveygoncharov/task14:latest

    - name: docker run via image
      #shell: docker stop my_container && docker rm $(docker ps -a -q)
      shell: docker run --name container_amazon -d -p 80:80 matveygoncharov/task14:latest
      #shell: docker stop my_container && docker rm $(docker ps -a -q)
      #notify: restart docker
      when: ansible_os_family == "RedHat"
    
    - name: docker run via image 2
      shell: docker run --name container_ubuntu -d -p 80:80 matveygoncharov/task14:latest
      when: ansible_os_family == "Debian"

  # restart docker daemon
  handlers: 
  - name: restart docker
    service: name=docker state=restarted
